export const ADD_READINGS = "ADD_READINGS";
export const ADD_READINGS_REQUEST = "ADD_READINGS_REQUEST";
export const ADD_READINGS_FAIL = "ADD_READINGS_FAIL";
export const SELECT_READING = "SELECT_READING";
